# Wordpress stack

# php-fpm server
version: '3.1'
services:
  php-fpm:
    image: openbridge/ob_php-fpm
    container_name: wpdock-php
    restart: always
    # specific config files for dev, staging and prod
    env_file:
      - ./env/dev.env
    ports:
      - 9000:9000
    # use in memory caching
    tmpfs: /var/cache
    tty: true
    volumes:
       - $HOST_DOCROOT:/usr/share/nginx/html
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    ulimits:
      nproc: 65535
      nofile:
          soft: 49999
          hard: 99999

  mariabdb: